# Generated by Django 5.2.6 on 2026-03-28 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='seats_available',
            new_name='seats',
        ),
    ]
